main_classes
Yazychkov/IntentClassification pull request #2
Opened 2021-06-10 21:33 UTC by Yazychkov

Класс Matcher,
метод load_data() - загружает опорные фразы
метод match(str) - должен вернуть название интента или None, если не нашел точного совпадения по опорной фразе
------------------------------------------------------------------------------------------------------------------------------------------
Класс Skillserver,
При создании скиллсервера ему должен приходить список активных интентов, экземпляры которых должны храниться у него в словаре.
Так же тут создается экземпляр матчера.
Сюда же в метод get_answer(chat_id, phrase) -> должен приходить TelegramChecker
------------------------------------------------------------------------------------------------------------------------------------------
Абстрактный класс Skill,
Должен реализовывать интерфейс для скиллов.
Нужны методы:
get_answer(phrase, context=None) -> str
load_data() -> None
------------------------------------------------------------------------------------------------------------------------------------------
Класс Context,
chat_id,
поля name
------------------------------------------------------------------------------------------------------------------------------------------
Класс HumorIntent, 
который будет выдавать случайный анекдот

2021-06-11 17:01 UTC, statz requested changes

2021-06-11 17:01 UTC, statz commented on HumorIntent.py
> +class Humorintent(Skill):
HumorIntent, а сам файл лучше вынести в папку intents и назвать просто humor

2021-06-11 17:01 UTC, statz commented on HumorIntent.py
> +# print(joke1.get_random_joke())
новая строка в конце файла 
если хочется тестить отдельный запуск файла, то лучше использовать if __name__ == '__main__'

2021-06-11 17:01 UTC, statz commented on class_Context.py
> +
пустые строчки

2021-06-11 17:01 UTC, statz commented on class_Matcher.py
> +        # self.skillserver = Skillserver()
надо убрать

2021-06-11 17:01 UTC, statz commented on class_Skillserver.py
> +        intent_dict = {
надо создать один раз в конструкторе

2021-06-11 17:01 UTC, statz commented on class_Skillserver.py
> +        for key in intent_dict:
ну сто раз уже проходили)
 if key in intent_dict: 
     return intent_dict[key]

2021-06-11 17:01 UTC, statz commented on class_Skillserver.py
> +        # chat_id = TelegramChecker()  #получение chat_id из класса чекер
надо удалять неиспользуемые строчки

2021-06-11 17:01 UTC, statz commented on class_Skillserver.py
> +        phrase = ('ответ от скиллсервера {}'.format())
так а где ответ-то? надо матчер вызвать, а потом интент

2021-06-11 17:01 UTC, statz commented on class_Skillserver.py
> +
прогони код через black

2021-06-12 07:23 UTC, statz requested changes

2021-06-12 07:23 UTC, statz commented on class_Context.py
> +
Не надо файлы называть class_, просто context.py

2021-06-12 07:23 UTC, statz commented on class_Matcher.py
> +        if input_phrase in dict_data.keys():
keys не нужны

2021-06-12 07:23 UTC, statz commented on class_Matcher.py
> +        dict_data = json.loads(self.data)
self.data же уже dict

2021-06-12 07:23 UTC, statz commented on class_Skill.py
> +    def get_answer(self, phrase, context=None) -> str:
from abc import ABCMeta, abstractmethod

class Skill(metaclass=ABCMeta):

    @abstractmethod
    def get_answer(self, phrase, context=None) -> str:
        pass

2021-06-12 07:23 UTC, statz commented on class_Skillserver.py
> +from IntentClassification.intent.humor import HumorIntent
IntentClassification. не нужно

2021-06-12 08:34 UTC, statz requested changes

2021-06-12 08:34 UTC, statz commented on class_Matcher.py
> +    def match(self, input_phrase):
добавить контекст

2021-06-12 08:34 UTC, statz commented on intent/humor.py
> +        with open("../anek_fixed.sql", "r", encoding="Windows-1251") as file:
Вынести в load_data

2021-06-14 14:19 UTC, statz requested changes

2021-06-14 14:19 UTC, statz commented on Skillserver.py
> +            "humor": HumorIntent   # с () - объект, без () - класс
Как раз нужно с ()

2021-06-14 14:19 UTC, statz commented on Matcher.py
> +        if phrase in self.load_data():
зачем каждый раз загружать?

2021-06-14 14:19 UTC, statz commented on .gitignore
> +*.json
пустая строка

2021-06-14 14:19 UTC, statz commented on Context.py
> +            for key, value in file:
какой смысл у этого цикла?

2021-06-14 14:19 UTC, statz commented on Context.py
> +            file.seek(0)
truncate

2021-06-14 14:19 UTC, statz commented on intent/humor.py
> +        self.file
Здесь мы должны считать один раз все шутки и положить в список

2021-06-14 14:19 UTC, statz commented on intent/humor.py
> +    def get_answer(self) -> str:
а здесь просто через random.choice выбрать случайную

2021-06-14 14:19 UTC, statz commented on Skillserver.py
> +        intent_result = self.check_intent(res)
тут же должен вызвыаться get_answer

2021-06-14 14:19 UTC, statz commented on Context.py
> +
с маленькой буквы названия файлов

2021-06-14 14:22 UTC, Yazychkov commented on Context.py
> +            for key, value in file:
проверка на нового пользователя

2021-06-14 14:27 UTC, statz commented on Context.py
> +            for key, value in file:
и что произойдет, если пользователь уже есть?

2021-06-14 14:29 UTC, Yazychkov commented on Context.py
> +            for key, value in file:
ничего, не будет снова заносить его данные

2021-06-14 14:32 UTC, statz commented on Context.py
> +            for key, value in file:
break прерывает цикл, а не функцию, так что всё равно перезапишется

2021-06-14 14:32 UTC, statz commented on Context.py
> +            for key, value in file:
ну и опять  проходишь по словарю, чтобы проверить наличие элемента,

2021-06-17 06:51 UTC, statz commented on intent/humor.py
> +        with open("anek_fixed.sql", "r", encoding="Windows-1251") as file:
А где этот файл взять? лучше добавить возможность скачать его, если нет локально

2021-06-17 06:51 UTC, statz commented on matcher.py
> +        if phrase in self.data:
return self.data.get(phrase) 
вместо тысячи слов)

2021-06-17 06:51 UTC, statz commented on skillserver.py
> +        if text in self.intent_dict:
.get

2021-06-17 06:51 UTC, statz commented on context.py
> +    def check_user(self, chat_id: int, name: str):
у нас в классе должeн быть self.name и self.chat_id. И два метода: save  и load. Один сохраняет контекст, второй - загружает

2021-06-17 06:51 UTC, statz commented on matcher.py
> +            self.data = json.load(file)
Надо переменные в init объявлять

2021-06-17 14:02 UTC, statz approved these changes

2021-06-17 14:02 UTC, merged